#ifndef _SPALAXCONF_H_
#define _SPALAXCONF_H_
#include "ch.h"
#include "hal.h"

#define ADIS16405_SPID         SPID2
#define ADIS16405_SPI_CS_PORT  GPIOA
#define ADIS16405_SPI_CS_PIN   GPIOA_ADIS_CS
#define ADIS16405_NRST_PORT    GPIOA
#define ADIS16405_NRST_PIN     GPIOA_ADIS_NRST

#define MPU9250_SPID         SPID2
#define MPU9250_SPI_CS_PORT  GPIOB
#define MPU9250_SPI_CS_PIN   GPIOB_MPU_CS

#define MS5611_SPID        SPID1
#define MS5611_SPI_CS_PORT GPIOC
#define MS5611_SPI_CS_PIN  GPIOC_BARO_CS

#define HAS_UBLOX 0

#define BAD_THING_HANDLER_BEEP_ENABLED 0
#define BAD_THING_HANDLER_BUZZER_PORT
#define BAD_THING_HANDLER_BUZZER_PIN

#define BAD_THING_HANDLER_OK_LED_PORT GPIOC
#define BAD_THING_HANDLER_OK_LED_PIN GPIOC_LED_GREEN
#define BAD_THING_HANDLER_NOK_LED_PORT GPIOC
#define BAD_THING_HANDLER_NOK_LED_PIN GPIOC_LED_RED

#define BAD_THIND_HANDLER_HAS_SENSOR_LEDS 0
#define BAD_THING_HANDLER_SENSOR_OK_LED_PORT
#define BAD_THING_HANDLER_SENSOR_OK_LED_PIN
#define BAD_THING_HANDLER_SENSOR_NOK_LED_PORT
#define BAD_THING_HANDLER_SENSOR_NOK_LED_PIN

extern const EXTConfig extcfg;

#endif /* _SPALAXCONF_H_ */
