#ifndef _SPALAXCONF_H_
#define _SPALAXCONF_H_
#include "ch.h"
#include "hal.h"

#define ADIS16405_SPID         SPID3
#define ADIS16405_SPI_CS_PORT  GPIOA
#define ADIS16405_SPI_CS_PIN   GPIOA_ESPI_NSS
#define ADIS16405_NRST_PORT    GPIOD
#define ADIS16405_NRST_PIN     GPIOD_CAN1_TX

#define MPU9250_SPID         SPID1
#define MPU9250_SPI_CS_PORT  GPIOA
#define MPU9250_SPI_CS_PIN   GPIOA_MPU_NSS

#define MS5611_SPID        SPID2
#define MS5611_SPI_CS_PORT GPIOB
#define MS5611_SPI_CS_PIN  GPIOB_ALT_NSS

#define HAS_UBLOX 1

#define BAD_THING_HANDLER_BEEP_ENABLED 0
#define BAD_THING_HANDLER_BUZZER_PORT GPIOE
#define BAD_THING_HANDLER_BUZZER_PIN GPIOE_STAT_BUZZER

#define BAD_THING_HANDLER_OK_LED_PORT GPIOE
#define BAD_THING_HANDLER_OK_LED_PIN GPIOE_STAT_IMU
#define BAD_THING_HANDLER_NOK_LED_PORT GPIOE
#define BAD_THING_HANDLER_NOK_LED_PIN GPIOE_STAT_NIMU

#define BAD_THIND_HANDLER_HAS_SENSOR_LEDS 1
#define BAD_THING_HANDLER_SENSOR_OK_LED_PORT GPIOB
#define BAD_THING_HANDLER_SENSOR_OK_LED_PIN GPIOB_STAT_SENSORS
#define BAD_THING_HANDLER_SENSOR_NOK_LED_PORT GPIOE
#define BAD_THING_HANDLER_SENSOR_NOK_LED_PIN GPIOE_STAT_NSENSORS

extern const EXTConfig extcfg;

#endif /* _SPALAXCONF_H_ */
