#ifndef MISSION_H
#define MISSION_H

typedef enum {
	STATE_PAD = 0, STATE_IGNITION, STATE_POWERED_ASCENT, STATE_FREE_ASCENT,
	STATE_APOGEE, STATE_DROGUE_DESCENT, STATE_RELEASE_MAIN,
	STATE_MAIN_DESCENT, STATE_LAND, STATE_LANDED, NUM_STATES
} state_t;

void print_state_transition(int from_state, int to_state);

#endif /* MISSION_H */